FROM node:current-alpine3.18

ENV PORT 3001

# Create app directory

WORKDIR /app

# Installing dependencies
COPY package*.json /app
RUN npm install

# Copying source files
COPY . /app
EXPOSE 3001

# Running the app
CMD "npm" "run" "dev"